version: "2.1"

volumes:
  jenkins-db-volume:
    external: false

networks:
  default:
    external:
      name: devsecops-sample

services:
  jenkins:
    image: jenkins-devsecops
    build:
      dockerfile: jenkins.dockerfile
      context: .
    ports:
      - "5555:8080"
      - "50000:50000"
    volumes:
      - "jenkins-db-volume:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"